package com.yetithehimalayankitchenbaner.service;

import com.yetithehimalayankitchenbaner.dto.BlogPostDto;
import com.yetithehimalayankitchenbaner.exception.ResourceNotFoundException;
import com.yetithehimalayankitchenbaner.model.BlogPost;
import com.yetithehimalayankitchenbaner.repository.BlogPostRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class BlogService {

    private final BlogPostRepository blogPostRepository;

    @Autowired
    public BlogService(BlogPostRepository blogPostRepository) {
        this.blogPostRepository = blogPostRepository;
    }

    public List<BlogPostDto> getAllBlogPosts() {
        return blogPostRepository.findAll().stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }

    public BlogPostDto getBlogPostById(UUID id) {
        BlogPost blogPost = blogPostRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Blog post not found with ID: " + id));
        return convertToDto(blogPost);
    }

    public BlogPostDto createBlogPost(BlogPostDto blogPostDto) {
        BlogPost blogPost = convertToEntity(blogPostDto);
        BlogPost savedBlogPost = blogPostRepository.save(blogPost);
        return convertToDto(savedBlogPost);
    }

    public BlogPostDto updateBlogPost(UUID id, BlogPostDto blogPostDto) {
        BlogPost existingBlogPost = blogPostRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Blog post not found with ID: " + id));

        existingBlogPost.setTitle(blogPostDto.getTitle());
        existingBlogPost.setContent(blogPostDto.getContent());
        existingBlogPost.setAuthor(blogPostDto.getAuthor());
        existingBlogPost.setPublicationDate(blogPostDto.getPublicationDate());
        existingBlogPost.setImageUrl(blogPostDto.getImageUrl());

        BlogPost updatedBlogPost = blogPostRepository.save(existingBlogPost);
        return convertToDto(updatedBlogPost);
    }

    public void deleteBlogPost(UUID id) {
        if (!blogPostRepository.existsById(id)) {
            throw new ResourceNotFoundException("Blog post not found with ID: " + id);
        }
        blogPostRepository.deleteById(id);
    }

    private BlogPostDto convertToDto(BlogPost blogPost) {
        return BlogPostDto.builder()
                .id(blogPost.getId())
                .title(blogPost.getTitle())
                .content(blogPost.getContent())
                .author(blogPost.getAuthor())
                .publicationDate(blogPost.getPublicationDate())
                .imageUrl(blogPost.getImageUrl())
                .build();
    }

    private BlogPost convertToEntity(BlogPostDto blogPostDto) {
        BlogPost blogPost = new BlogPost();
        blogPost.setId(blogPostDto.getId()); // ID might be null for new posts, will be generated by JPA
        blogPost.setTitle(blogPostDto.getTitle());
        blogPost.setContent(blogPostDto.getContent());
        blogPost.setAuthor(blogPostDto.getAuthor());
        blogPost.setPublicationDate(blogPostDto.getPublicationDate());
        blogPost.setImageUrl(blogPostDto.getImageUrl());
        return blogPost;
    }
}